/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef IOP_HEADER_GUARD_core_TYPES_H
#define IOP_HEADER_GUARD_core_TYPES_H

#include "core-tdef.iop.h"

extern iop_enum_t const core__log_level__e;
IOP_ENUM(core__log_level);

extern iop_enum_t const core__iop_http_method__e;
IOP_ENUM(core__iop_http_method);

#endif
