/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef IOP_HEADER_GUARD_core_H
#define IOP_HEADER_GUARD_core_H

#include "core-t.iop.h"

typedef struct core__log__set_root_level_args__t core__log__set_root_level_args__t;
typedef IOP_ARRAY_OF(core__log__set_root_level_args__t) core__log__set_root_level_args__array_t;

typedef struct core__log__set_root_level_res__t core__log__set_root_level_res__t;
typedef IOP_ARRAY_OF(core__log__set_root_level_res__t) core__log__set_root_level_res__array_t;

typedef iop__void__t core__log__set_root_level_exn__t;
typedef iop__void__t core__log__reset_root_level_args__t;
typedef struct core__log__reset_root_level_res__t core__log__reset_root_level_res__t;
typedef IOP_ARRAY_OF(core__log__reset_root_level_res__t) core__log__reset_root_level_res__array_t;

typedef iop__void__t core__log__reset_root_level_exn__t;
typedef struct core__log__set_logger_level_args__t core__log__set_logger_level_args__t;
typedef IOP_ARRAY_OF(core__log__set_logger_level_args__t) core__log__set_logger_level_args__array_t;

typedef struct core__log__set_logger_level_res__t core__log__set_logger_level_res__t;
typedef IOP_ARRAY_OF(core__log__set_logger_level_res__t) core__log__set_logger_level_res__array_t;

typedef iop__void__t core__log__set_logger_level_exn__t;
typedef struct core__log__reset_logger_level_args__t core__log__reset_logger_level_args__t;
typedef IOP_ARRAY_OF(core__log__reset_logger_level_args__t) core__log__reset_logger_level_args__array_t;

typedef struct core__log__reset_logger_level_res__t core__log__reset_logger_level_res__t;
typedef IOP_ARRAY_OF(core__log__reset_logger_level_res__t) core__log__reset_logger_level_res__array_t;

typedef iop__void__t core__log__reset_logger_level_exn__t;
typedef struct core__log__list_loggers_args__t core__log__list_loggers_args__t;
typedef IOP_ARRAY_OF(core__log__list_loggers_args__t) core__log__list_loggers_args__array_t;

typedef struct core__log__list_loggers_res__t core__log__list_loggers_res__t;
typedef IOP_ARRAY_OF(core__log__list_loggers_res__t) core__log__list_loggers_res__array_t;

typedef iop__void__t core__log__list_loggers_exn__t;

/*----- interface core.Log -----*/
struct core__log__set_root_level_args__t {
    core__log_level__t level;
    bool     force_all;
    bool     is_silent;
};
EXPORT iop_struct_t const core__log__set_root_level_args__s;
EXPORT iop_struct_t const * const nonnull core__log__set_root_level_args__sp;
struct core__log__set_root_level_res__t {
    core__log_level__t level;
};
EXPORT iop_struct_t const core__log__set_root_level_res__s;
EXPORT iop_struct_t const * const nonnull core__log__set_root_level_res__sp;
#define core__log__set_root_level__rpc__tag    0x0001
#define core__log__set_root_level__rpc__async  0
#define core__log__set_root_level__rpc         (core__log__if.funs + 0)

struct core__log__reset_root_level_res__t {
    core__log_level__t level;
};
EXPORT iop_struct_t const core__log__reset_root_level_res__s;
EXPORT iop_struct_t const * const nonnull core__log__reset_root_level_res__sp;
#define core__log__reset_root_level__rpc__tag    0x0002
#define core__log__reset_root_level__rpc__async  0
#define core__log__reset_root_level__rpc         (core__log__if.funs + 1)

struct core__log__set_logger_level_args__t {
    lstr_t   full_name;
    core__log_level__t level;
    bool     force_all;
    bool     is_silent;
};
EXPORT iop_struct_t const core__log__set_logger_level_args__s;
EXPORT iop_struct_t const * const nonnull core__log__set_logger_level_args__sp;
struct core__log__set_logger_level_res__t {
    core__log_level__t level;
};
EXPORT iop_struct_t const core__log__set_logger_level_res__s;
EXPORT iop_struct_t const * const nonnull core__log__set_logger_level_res__sp;
#define core__log__set_logger_level__rpc__tag    0x0003
#define core__log__set_logger_level__rpc__async  0
#define core__log__set_logger_level__rpc         (core__log__if.funs + 2)

struct core__log__reset_logger_level_args__t {
    lstr_t   full_name;
};
EXPORT iop_struct_t const core__log__reset_logger_level_args__s;
EXPORT iop_struct_t const * const nonnull core__log__reset_logger_level_args__sp;
struct core__log__reset_logger_level_res__t {
    core__log_level__t level;
};
EXPORT iop_struct_t const core__log__reset_logger_level_res__s;
EXPORT iop_struct_t const * const nonnull core__log__reset_logger_level_res__sp;
#define core__log__reset_logger_level__rpc__tag    0x0004
#define core__log__reset_logger_level__rpc__async  0
#define core__log__reset_logger_level__rpc         (core__log__if.funs + 3)

struct core__log__list_loggers_args__t {
    lstr_t           prefix;
};
EXPORT iop_struct_t const core__log__list_loggers_args__s;
EXPORT iop_struct_t const * const nonnull core__log__list_loggers_args__sp;
struct core__log__list_loggers_res__t {
    core__logger_configuration__array_t loggers;
};
EXPORT iop_struct_t const core__log__list_loggers_res__s;
EXPORT iop_struct_t const * const nonnull core__log__list_loggers_res__sp;
#define core__log__list_loggers__rpc__tag    0x0005
#define core__log__list_loggers__rpc__async  0
#define core__log__list_loggers__rpc         (core__log__if.funs + 4)

EXPORT iop_iface_t const core__log__if;
EXPORT iop_iface_t const * const nonnull core__log__ifp;


/*----- module core.Core -----*/
#define core__core__log__TAG    0x4000
#define core__core__log(a)      core__log__##a
#define core__core__log__alias  (core__core__mod.ifaces + 0)

EXPORT iop_mod_t const core__core__mod;
EXPORT iop_mod_t const * const nonnull core__core__modp;


/*----- package core -----*/
EXPORT iop_pkg_t const core__pkg;
EXPORT iop_pkg_t const * const nonnull core__pkgp;

#endif
