/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef linux
#  warning "%s assumed linux alignments"
#endif
#ifndef __x86_64__
#  warning "core.iop assumed x86_64 alignments"
#endif

#include "core.iop.h"

/* Enum core.LogLevel {{{ */

static int const core__log_level__values[] = {
 0, 1, 2, 3, 4, 5, 6, 7,
};
static int const iop__ranges__1[] = {
    0, 0,
    8,
};
static const lstr_t core__log_level__names[] = {
    LSTR_IMMED("EMERG"),
    LSTR_IMMED("ALERT"),
    LSTR_IMMED("CRIT"),
    LSTR_IMMED("ERR"),
    LSTR_IMMED("WARNING"),
    LSTR_IMMED("NOTICE"),
    LSTR_IMMED("INFO"),
    LSTR_IMMED("DEBUG"),
};
iop_enum_t const core__log_level__e = {
    .name       = LSTR_IMMED("LogLevel"),
    .fullname   = LSTR_IMMED("core.LogLevel"),
    .names      = core__log_level__names,
    .values     = core__log_level__values,
    .ranges     = iop__ranges__1,
    .ranges_len = countof(iop__ranges__1) / 2,
    .enum_len   = 8,
};

/* }}} */
/* Package core {{{ */

static const iop_pkg_t *const core__deps[] = {
    NULL,
};

static const iop_enum_t *const core__enums[] = {
    &core__log_level__e,
    NULL,
};

static const iop_struct_t *const core__structs[] = {
    NULL,
};

static const iop_iface_t *const core__ifaces[] = {
    NULL,
};

static const iop_mod_t *const core__mods[] = {
    NULL,
};

iop_pkg_t const core__pkg = {
    .name    = LSTR_IMMED("core"),
    .deps    = core__deps,
    .enums   = core__enums,
    .structs = core__structs,
    .ifaces  = core__ifaces,
    .mods    = core__mods,
};

/* }}} */

