/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef IOP_HEADER_GUARD_ic_TYPEDEFS_H
#define IOP_HEADER_GUARD_ic_TYPEDEFS_H

#include <lib-common/core.h>
#include <lib-common/iop-internals.h>

typedef enum ic__ic_priority__t {
    IC_PRIORITY_LOW,
    IC_PRIORITY_NORMAL,
    IC_PRIORITY_HIGH,
} ic__ic_priority__t;
typedef IOP_ARRAY_OF(enum ic__ic_priority__t) ic__ic_priority__array_t;
#ifdef OPT_OF
typedef OPT_OF(enum ic__ic_priority__t) ic__ic_priority__opt_t;
#else
typedef IOP_OPT_OF(enum ic__ic_priority__t) ic__ic_priority__opt_t;
#endif
#define IC_PRIORITY_count 3
#define IC_PRIORITY_min   0
#define IC_PRIORITY_max   2

typedef struct ic__tracer__t ic__tracer__t;
typedef IOP_ARRAY_OF(ic__tracer__t) ic__tracer__array_t;

typedef struct ic__simple_hdr__t ic__simple_hdr__t;
typedef IOP_ARRAY_OF(ic__simple_hdr__t) ic__simple_hdr__array_t;

typedef struct ic__route__t ic__route__t;
typedef IOP_ARRAY_OF(ic__route__t *nonnull ) ic__route__array_t;

typedef struct ic__routing_hdr__t ic__routing_hdr__t;
typedef IOP_ARRAY_OF(ic__routing_hdr__t) ic__routing_hdr__array_t;

typedef struct ic__hdr__t ic__hdr__t;
typedef IOP_ARRAY_OF(ic__hdr__t) ic__hdr__array_t;

#endif
