/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef IOP_HEADER_GUARD_ic_TYPEDEFS_H
#define IOP_HEADER_GUARD_ic_TYPEDEFS_H

#include <lib-common/iop.h>

typedef struct ic__simple_hdr__t ic__simple_hdr__t;
typedef IOP_ARRAY_OF(ic__simple_hdr__t) ic__simple_hdr__array_t;

typedef struct ic__hdr__t ic__hdr__t;
typedef IOP_ARRAY_OF(ic__hdr__t) ic__hdr__array_t;

#endif
