/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef IOP_HEADER_GUARD_ic_H
#define IOP_HEADER_GUARD_ic_H

#include "ic-t.iop.h"


/*----- package ic -----*/
extern iop_pkg_t const ic__pkg;

#endif
