/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/

#include "ic.iop.h"

/* Structure ic.SimpleHdr {{{ */

static iop_field_t const ic__simple_hdr__desc_fields[] = {
    {
        .name      = CLSTR_IMMED("login"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_OPTIONAL,
        .type      = IOP_T_STRING,
        .data_offs = offsetof(ic__simple_hdr__t, login),
    },
    {
        .name      = CLSTR_IMMED("password"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_OPTIONAL,
        .type      = IOP_T_STRING,
        .data_offs = offsetof(ic__simple_hdr__t, password),
    },
    {
        .name      = CLSTR_IMMED("kind"),
        .tag       = 3,
        .tag_len   = 0,
        .repeat    = IOP_R_OPTIONAL,
        .type      = IOP_T_STRING,
        .data_offs = offsetof(ic__simple_hdr__t, kind),
    },
    {
        .name      = CLSTR_IMMED("payload"),
        .tag       = 4,
        .tag_len   = 0,
        .repeat    = IOP_R_DEFVAL,
        .type      = IOP_T_I32,
        .data_offs = offsetof(ic__simple_hdr__t, payload),
        .defval    = { .u64 = 0xffffffffffffffff },
    },
};
static int const ic__simple_hdr__s_ranges[] = {
    0, 1,
    4,
};
const iop_struct_t ic__simple_hdr__s = {
    .fullname   = CLSTR_IMMED("ic.SimpleHdr"),
    .fields     = ic__simple_hdr__desc_fields,
    .ranges     = ic__simple_hdr__s_ranges,
    .fields_len = countof(ic__simple_hdr__desc_fields),
    .ranges_len = countof(ic__simple_hdr__s_ranges) / 2,
    .size       = sizeof(ic__simple_hdr__t),
};

/* }}} */
/* Union ic.Hdr {{{ */

static iop_field_t const ic__hdr__desc_fields[] = {
    {
        .name      = CLSTR_IMMED("simple"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_STRUCT,
        .data_offs = offsetof(ic__hdr__t, simple),
        .size      = sizeof(ic__simple_hdr__t),
        .desc      = &ic__simple_hdr__s,
    },
};
static int const ic__hdr__s_ranges[] = {
    0, 1,
    1,
};
const iop_struct_t ic__hdr__s = {
    .fullname   = CLSTR_IMMED("ic.Hdr"),
    .fields     = ic__hdr__desc_fields,
    .ranges     = ic__hdr__s_ranges,
    .fields_len = countof(ic__hdr__desc_fields),
    .ranges_len = countof(ic__hdr__s_ranges) / 2,
    .size       = sizeof(ic__hdr__t),
    .is_union   = true,
};

/* }}} */

