/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef IOP_HEADER_GUARD_iop_TYPEDEFS_H
#define IOP_HEADER_GUARD_iop_TYPEDEFS_H

#include <lib-common/core.h>
#include <lib-common/iop-internals.h>

typedef enum iop__int_size__t {
    INT_SIZE_S8,
    INT_SIZE_S16,
    INT_SIZE_S32,
    INT_SIZE_S64,
} iop__int_size__t;
typedef IOP_ARRAY_OF(enum iop__int_size__t) iop__int_size__array_t;
#ifdef OPT_OF
typedef OPT_OF(enum iop__int_size__t) iop__int_size__opt_t;
#else
typedef IOP_OPT_OF(enum iop__int_size__t) iop__int_size__opt_t;
#endif
#define INT_SIZE_count 4
#define INT_SIZE_min   0
#define INT_SIZE_max   3

typedef enum iop__string_type__t {
    STRING_TYPE_STRING,
    STRING_TYPE_BYTES,
    STRING_TYPE_XML,
} iop__string_type__t;
typedef IOP_ARRAY_OF(enum iop__string_type__t) iop__string_type__array_t;
#ifdef OPT_OF
typedef OPT_OF(enum iop__string_type__t) iop__string_type__opt_t;
#else
typedef IOP_OPT_OF(enum iop__string_type__t) iop__string_type__opt_t;
#endif
#define STRING_TYPE_count 3
#define STRING_TYPE_min   0
#define STRING_TYPE_max   2

typedef struct iop__int_type__t iop__int_type__t;
typedef IOP_ARRAY_OF(iop__int_type__t) iop__int_type__array_t;

typedef struct iop__iop_type__t iop__iop_type__t;
typedef IOP_ARRAY_OF(iop__iop_type__t) iop__iop_type__array_t;

typedef struct iop__package_elem__t iop__package_elem__t;
typedef IOP_ARRAY_OF(iop__package_elem__t *nonnull ) iop__package_elem__array_t;

typedef struct iop__value__t iop__value__t;
typedef IOP_ARRAY_OF(iop__value__t) iop__value__array_t;

typedef struct iop__opt_info__t iop__opt_info__t;
typedef IOP_ARRAY_OF(iop__opt_info__t) iop__opt_info__array_t;

typedef struct iop__field__t iop__field__t;
typedef IOP_ARRAY_OF(iop__field__t) iop__field__array_t;

typedef struct iop__structure__t iop__structure__t;
typedef IOP_ARRAY_OF(iop__structure__t *nonnull ) iop__structure__array_t;

typedef struct iop__struct__t iop__struct__t;
typedef IOP_ARRAY_OF(iop__struct__t *nonnull ) iop__struct__array_t;

typedef struct iop__union__t iop__union__t;
typedef IOP_ARRAY_OF(iop__union__t *nonnull ) iop__union__array_t;

typedef struct iop__package__t iop__package__t;
typedef IOP_ARRAY_OF(iop__package__t) iop__package__array_t;

#endif
