/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef IOP_HEADER_GUARD_iop_H
#define IOP_HEADER_GUARD_iop_H

#include "iop-t.iop.h"



/*----- package iop -----*/
EXPORT iop_pkg_t const iop__pkg;
EXPORT iop_pkg_t const * const nonnull iop__pkgp;

#endif
