/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#if !defined(linux) && !defined(__APPLE__)
#  warning "iopsq.iop assumed linux alignments"
#endif
#ifndef __x86_64__
#  warning "iopsq.iop assumed x86_64 alignments"
#endif

#include "iopsq.iop.h"

/* Enum iopsq.IntSize {{{ */

static int const iopsq__int_size__values[] = {
 0, 1, 2, 3,
};
static int const iop__ranges__1[] = {
    0, 0,
    4,
};
static const lstr_t iopsq__int_size__names[] = {
    LSTR_IMMED("S8"),
    LSTR_IMMED("S16"),
    LSTR_IMMED("S32"),
    LSTR_IMMED("S64"),
};
iop_enum_t const iopsq__int_size__e = {
    .name         = LSTR_IMMED("IntSize"),
    .fullname     = LSTR_IMMED("iopsq.IntSize"),
    .names        = iopsq__int_size__names,
    .values       = iopsq__int_size__values,
    .ranges       = iop__ranges__1,
    .ranges_len   = countof(iop__ranges__1) / 2,
    .enum_len     = 4,
};
iop_enum_t const * const iopsq__int_size__ep = &iopsq__int_size__e;

/* }}} */
/* Enum iopsq.StringType {{{ */

static int const iopsq__string_type__values[] = {
 0, 1, 2,
};
static int const iop__ranges__2[] = {
    0, 0,
    3,
};
static const lstr_t iopsq__string_type__names[] = {
    LSTR_IMMED("STRING"),
    LSTR_IMMED("BYTES"),
    LSTR_IMMED("XML"),
};
iop_enum_t const iopsq__string_type__e = {
    .name         = LSTR_IMMED("StringType"),
    .fullname     = LSTR_IMMED("iopsq.StringType"),
    .names        = iopsq__string_type__names,
    .values       = iopsq__string_type__values,
    .ranges       = iop__ranges__2,
    .ranges_len   = countof(iop__ranges__2) / 2,
    .enum_len     = 3,
};
iop_enum_t const * const iopsq__string_type__ep = &iopsq__string_type__e;

/* }}} */
/* Structure iopsq.IntType {{{ */

static iop_field_t const iopsq__int_type__desc_fields[] = {
    {
        .name      = LSTR_IMMED("isSigned"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_BOOL,
        .data_offs = offsetof(iopsq__int_type__t, is_signed),
        .size      = fieldsizeof(iopsq__int_type__t, is_signed),
    },
    {
        .name      = LSTR_IMMED("size"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_ENUM,
        .data_offs = offsetof(iopsq__int_type__t, size),
        .size      = fieldsizeof(iopsq__int_type__t, size),
        .u1        = { .en_desc = &iopsq__int_size__e },
    },
};
static int const iop__ranges__3[] = {
    0, 1,
    2,
};
const iop_struct_t iopsq__int_type__s = {
    .fullname   = LSTR_IMMED("iopsq.IntType"),
    .fields     = iopsq__int_type__desc_fields,
    .ranges     = iop__ranges__3,
    .ranges_len = countof(iop__ranges__3) / 2,
    .fields_len = countof(iopsq__int_type__desc_fields),
    .size       = sizeof(iopsq__int_type__t),
};
iop_struct_t const * const iopsq__int_type__sp = &iopsq__int_type__s;

/* }}} */
/* Union iopsq.IopType {{{ */

static int iopsq__iop_type__type_name__check(const void *ptr, int n)
{
    for (int j = 0; j < n; j++) {
        lstr_t    val = IOP_FIELD(lstr_t   , ptr, j);

        for (int c = 0; c < val.len; c++) {
            switch (val.s[c]) {
                case 'a' ... 'z':
                case 'A' ... 'Z':
                case '0' ... '9':
                case '.':
                    break;
                default:
                    iop_set_err("violation of constraint %s (%s) on field %s: %*pM",
                                "pattern", "[a-zA-Z0-9\\.]*", "typeName", LSTR_FMT_ARG(val));
                    return -1;
            }
        }
        if (val.len < 1) {
            iop_set_err("violation of constraint %s (%d) on field %s: length=%d",
                        "minLength", 1, "typeName", val.len);
            return -1;
        }
    }
    return 0;
}
static iop_field_attr_t const iopsq__iop_type__type_name__attrs[] = {
    {
        .type = 9,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("[a-zA-Z0-9\\.]*") } },
    },
    {
        .type = 7,
        .args = (iop_field_attr_arg_t[]){ { .v.i64 = 1LL } },
    },
};
static iop_field_attrs_t const iopsq__iop_type__desc_fields_attrs[] = {
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
    {
        .flags             = 640,
        .attrs_len         = 2,
        .check_constraints = &iopsq__iop_type__type_name__check,
        .attrs             = iopsq__iop_type__type_name__attrs,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
};
static iop_field_t const iopsq__iop_type__desc_fields[] = {
    {
        .name      = LSTR_IMMED("i"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_STRUCT,
        .data_offs = offsetof(iopsq__iop_type__t, i),
        .size      = sizeof(iopsq__int_type__t),
        .u1        = { .st_desc = &iopsq__int_type__s },
    },
    {
        .name      = LSTR_IMMED("b"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_VOID,
        .data_offs = offsetof(iopsq__iop_type__t, i),
    },
    {
        .name      = LSTR_IMMED("d"),
        .tag       = 3,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_VOID,
        .data_offs = offsetof(iopsq__iop_type__t, i),
    },
    {
        .name      = LSTR_IMMED("s"),
        .tag       = 4,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_ENUM,
        .data_offs = offsetof(iopsq__iop_type__t, s),
        .size      = fieldsizeof(iopsq__iop_type__t, s),
        .u1        = { .en_desc = &iopsq__string_type__e },
    },
    {
        .name      = LSTR_IMMED("v"),
        .tag       = 5,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_VOID,
        .data_offs = offsetof(iopsq__iop_type__t, i),
    },
    {
        .name      = LSTR_IMMED("typeName"),
        .tag       = 6,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_STRING,
        .data_offs = offsetof(iopsq__iop_type__t, type_name),
        .flags     = 1,
        .size      = fieldsizeof(iopsq__iop_type__t, type_name),
    },
    {
        .name      = LSTR_IMMED("array"),
        .tag       = 7,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_UNION,
        .data_offs = offsetof(iopsq__iop_type__t, array),
        .flags     = 4,
        .size      = sizeof(iopsq__iop_type__t),
        .u1        = { .st_desc = &iopsq__iop_type__s },
    },
};
static int const iop__ranges__4[] = {
    0, 1,
    7,
};
const iop_struct_t iopsq__iop_type__s = {
    .fullname   = LSTR_IMMED("iopsq.IopType"),
    .fields     = iopsq__iop_type__desc_fields,
    .ranges     = iop__ranges__4,
    .ranges_len = countof(iop__ranges__4) / 2,
    .fields_len = countof(iopsq__iop_type__desc_fields),
    .size       = sizeof(iopsq__iop_type__t),
    .flags      = 3,
    .is_union   = true,
    .fields_attrs = iopsq__iop_type__desc_fields_attrs,
};
iop_struct_t const * const iopsq__iop_type__sp = &iopsq__iop_type__s;

/* }}} */
/* Class iopsq.PackageElem {{{ */

static int iopsq__package_elem__name__check(const void *ptr, int n)
{
    for (int j = 0; j < n; j++) {
        lstr_t    val = IOP_FIELD(lstr_t   , ptr, j);

        for (int c = 0; c < val.len; c++) {
            switch (val.s[c]) {
                case 'a' ... 'z':
                case 'A' ... 'Z':
                case '0' ... '9':
                    break;
                default:
                    iop_set_err("violation of constraint %s (%s) on field %s: %*pM",
                                "pattern", "[a-zA-Z0-9]*", "name", LSTR_FMT_ARG(val));
                    return -1;
            }
        }
        if (val.len < 1) {
            iop_set_err("violation of constraint %s (%d) on field %s: length=%d",
                        "minLength", 1, "name", val.len);
            return -1;
        }
    }
    return 0;
}
static iop_field_attr_t const iopsq__package_elem__name__attrs[] = {
    {
        .type = 9,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("[a-zA-Z0-9]*") } },
    },
    {
        .type = 7,
        .args = (iop_field_attr_arg_t[]){ { .v.i64 = 1LL } },
    },
};
static iop_field_attrs_t const iopsq__package_elem__desc_fields_attrs[] = {
    {
        .flags             = 640,
        .attrs_len         = 2,
        .check_constraints = &iopsq__package_elem__name__check,
        .attrs             = iopsq__package_elem__name__attrs,
    },
};
static iop_field_t const iopsq__package_elem__desc_fields[] = {
    {
        .name      = LSTR_IMMED("name"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_STRING,
        .data_offs = offsetof(iopsq__package_elem__t, name),
        .flags     = 1,
        .size      = fieldsizeof(iopsq__package_elem__t, name),
    },
};
static int const iop__ranges__5[] = {
    0, 1,
    1,
};
static const iop_class_attrs_t iopsq__package_elem__class_s = {
    .is_abstract       = true,
    .class_id          = 0,
};
const iop_struct_t iopsq__package_elem__s = {
    .fullname   = LSTR_IMMED("iopsq.PackageElem"),
    .fields     = iopsq__package_elem__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(iopsq__package_elem__desc_fields),
    .size       = sizeof(iopsq__package_elem__t),
    .flags      = 15,
    .is_union   = false,
    .st_attrs   = NULL,
    .fields_attrs = iopsq__package_elem__desc_fields_attrs,
    {
        .class_attrs  = &iopsq__package_elem__class_s,
    }
};
iop_struct_t const * const iopsq__package_elem__sp = &iopsq__package_elem__s;

/* }}} */
/* Union iopsq.Value {{{ */

static iop_field_t const iopsq__value__desc_fields[] = {
    {
        .name      = LSTR_IMMED("i"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I64,
        .data_offs = offsetof(iopsq__value__t, i),
        .size      = fieldsizeof(iopsq__value__t, i),
    },
    {
        .name      = LSTR_IMMED("u"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_U64,
        .data_offs = offsetof(iopsq__value__t, u),
        .size      = fieldsizeof(iopsq__value__t, u),
    },
    {
        .name      = LSTR_IMMED("d"),
        .tag       = 3,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_DOUBLE,
        .data_offs = offsetof(iopsq__value__t, d),
        .size      = fieldsizeof(iopsq__value__t, d),
    },
    {
        .name      = LSTR_IMMED("s"),
        .tag       = 4,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_STRING,
        .data_offs = offsetof(iopsq__value__t, s),
        .size      = fieldsizeof(iopsq__value__t, s),
    },
    {
        .name      = LSTR_IMMED("b"),
        .tag       = 5,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_BOOL,
        .data_offs = offsetof(iopsq__value__t, b),
        .size      = fieldsizeof(iopsq__value__t, b),
    },
};
static int const iop__ranges__6[] = {
    0, 1,
    5,
};
const iop_struct_t iopsq__value__s = {
    .fullname   = LSTR_IMMED("iopsq.Value"),
    .fields     = iopsq__value__desc_fields,
    .ranges     = iop__ranges__6,
    .ranges_len = countof(iop__ranges__6) / 2,
    .fields_len = countof(iopsq__value__desc_fields),
    .size       = sizeof(iopsq__value__t),
    .is_union   = true,
};
iop_struct_t const * const iopsq__value__sp = &iopsq__value__s;

/* }}} */
/* Structure iopsq.OptInfo {{{ */

static iop_field_t const iopsq__opt_info__desc_fields[] = {
    {
        .name      = LSTR_IMMED("defVal"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_OPTIONAL,
        .type      = IOP_T_UNION,
        .data_offs = offsetof(iopsq__opt_info__t, def_val),
        .size      = sizeof(iopsq__value__t),
        .u1        = { .st_desc = &iopsq__value__s },
    },
};
const iop_struct_t iopsq__opt_info__s = {
    .fullname   = LSTR_IMMED("iopsq.OptInfo"),
    .fields     = iopsq__opt_info__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(iopsq__opt_info__desc_fields),
    .size       = sizeof(iopsq__opt_info__t),
};
iop_struct_t const * const iopsq__opt_info__sp = &iopsq__opt_info__s;

/* }}} */
/* Structure iopsq.Field {{{ */

static int iopsq__field__name__check(const void *ptr, int n)
{
    for (int j = 0; j < n; j++) {
        lstr_t    val = IOP_FIELD(lstr_t   , ptr, j);

        for (int c = 0; c < val.len; c++) {
            switch (val.s[c]) {
                case 'a' ... 'z':
                case 'A' ... 'Z':
                case '0' ... '9':
                    break;
                default:
                    iop_set_err("violation of constraint %s (%s) on field %s: %*pM",
                                "pattern", "[a-zA-Z0-9]*", "name", LSTR_FMT_ARG(val));
                    return -1;
            }
        }
        if (val.len < 1) {
            iop_set_err("violation of constraint %s (%d) on field %s: length=%d",
                        "minLength", 1, "name", val.len);
            return -1;
        }
    }
    return 0;
}
static iop_field_attr_t const iopsq__field__name__attrs[] = {
    {
        .type = 9,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("[a-zA-Z0-9]*") } },
    },
    {
        .type = 7,
        .args = (iop_field_attr_arg_t[]){ { .v.i64 = 1LL } },
    },
};
static iop_field_attrs_t const iopsq__field__desc_fields_attrs[] = {
    {
        .flags             = 640,
        .attrs_len         = 2,
        .check_constraints = &iopsq__field__name__check,
        .attrs             = iopsq__field__name__attrs,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
};
static iop_field_t const iopsq__field__desc_fields[] = {
    {
        .name      = LSTR_IMMED("name"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_STRING,
        .data_offs = offsetof(iopsq__field__t, name),
        .flags     = 1,
        .size      = fieldsizeof(iopsq__field__t, name),
    },
    {
        .name      = LSTR_IMMED("type"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_UNION,
        .data_offs = offsetof(iopsq__field__t, type),
        .size      = sizeof(iopsq__iop_type__t),
        .u1        = { .st_desc = &iopsq__iop_type__s },
    },
    {
        .name      = LSTR_IMMED("optional"),
        .tag       = 3,
        .tag_len   = 0,
        .repeat    = IOP_R_OPTIONAL,
        .type      = IOP_T_STRUCT,
        .data_offs = offsetof(iopsq__field__t, optional),
        .size      = sizeof(iopsq__opt_info__t),
        .u1        = { .st_desc = &iopsq__opt_info__s },
    },
    {
        .name      = LSTR_IMMED("tag"),
        .tag       = 4,
        .tag_len   = 0,
        .repeat    = IOP_R_OPTIONAL,
        .type      = IOP_T_U16,
        .data_offs = offsetof(iopsq__field__t, tag),
        .size      = fieldsizeof(iopsq__field__t, tag),
    },
    {
        .name      = LSTR_IMMED("isReference"),
        .tag       = 5,
        .tag_len   = 0,
        .repeat    = IOP_R_OPTIONAL,
        .type      = IOP_T_VOID,
        .data_offs = offsetof(iopsq__field__t, is_reference),
        .size      = fieldsizeof(iopsq__field__t, is_reference),
    },
};
const iop_struct_t iopsq__field__s = {
    .fullname   = LSTR_IMMED("iopsq.Field"),
    .fields     = iopsq__field__desc_fields,
    .ranges     = iop__ranges__6,
    .ranges_len = countof(iop__ranges__6) / 2,
    .fields_len = countof(iopsq__field__desc_fields),
    .size       = sizeof(iopsq__field__t),
    .flags      = 3,
    .fields_attrs = iopsq__field__desc_fields_attrs,
};
iop_struct_t const * const iopsq__field__sp = &iopsq__field__s;

/* }}} */
/* Class iopsq.Structure {{{ */

static iop_field_t const iopsq__structure__desc_fields[] = {
};
static int const iop__ranges__7[] = {
    0,
};
static const iop_class_attrs_t iopsq__structure__class_s = {
    .parent            = &iopsq__package_elem__s,
    .is_abstract       = true,
    .class_id          = 1,
};
const iop_struct_t iopsq__structure__s = {
    .fullname   = LSTR_IMMED("iopsq.Structure"),
    .fields     = iopsq__structure__desc_fields,
    .ranges     = iop__ranges__7,
    .ranges_len = countof(iop__ranges__7) / 2,
    .fields_len = countof(iopsq__structure__desc_fields),
    .size       = sizeof(iopsq__structure__t),
    .flags      = 13,
    .is_union   = false,
    .st_attrs   = NULL,
    .fields_attrs = NULL,
    {
        .class_attrs  = &iopsq__structure__class_s,
    }
};
iop_struct_t const * const iopsq__structure__sp = &iopsq__structure__s;

/* }}} */
/* Class iopsq.Struct {{{ */

static iop_field_t const iopsq__struct__desc_fields[] = {
    {
        .name      = LSTR_IMMED("fields"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REPEATED,
        .type      = IOP_T_STRUCT,
        .data_offs = offsetof(iopsq__struct__t, fields),
        .size      = sizeof(iopsq__field__t),
        .u1        = { .st_desc = &iopsq__field__s },
    },
};
static const iop_class_attrs_t iopsq__struct__class_s = {
    .parent            = &iopsq__structure__s,
    .class_id          = 2,
};
const iop_struct_t iopsq__struct__s = {
    .fullname   = LSTR_IMMED("iopsq.Struct"),
    .fields     = iopsq__struct__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(iopsq__struct__desc_fields),
    .size       = sizeof(iopsq__struct__t),
    .flags      = 15,
    .is_union   = false,
    .st_attrs   = NULL,
    .fields_attrs = NULL,
    {
        .class_attrs  = &iopsq__struct__class_s,
    }
};
iop_struct_t const * const iopsq__struct__sp = &iopsq__struct__s;

/* }}} */
/* Structure iopsq.EnumVal {{{ */

static int iopsq__enum_val__name__check(const void *ptr, int n)
{
    for (int j = 0; j < n; j++) {
        lstr_t    val = IOP_FIELD(lstr_t   , ptr, j);

        for (int c = 0; c < val.len; c++) {
            switch (val.s[c]) {
                case 'A' ... 'Z':
                case '0' ... '9':
                case '_':
                    break;
                default:
                    iop_set_err("violation of constraint %s (%s) on field %s: %*pM",
                                "pattern", "[A-Z0-9_]*", "name", LSTR_FMT_ARG(val));
                    return -1;
            }
        }
        if (val.len < 1) {
            iop_set_err("violation of constraint %s (%d) on field %s: length=%d",
                        "minLength", 1, "name", val.len);
            return -1;
        }
    }
    return 0;
}
static iop_field_attr_t const iopsq__enum_val__name__attrs[] = {
    {
        .type = 9,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("[A-Z0-9_]*") } },
    },
    {
        .type = 7,
        .args = (iop_field_attr_arg_t[]){ { .v.i64 = 1LL } },
    },
};
static iop_field_attrs_t const iopsq__enum_val__desc_fields_attrs[] = {
    {
        .flags             = 640,
        .attrs_len         = 2,
        .check_constraints = &iopsq__enum_val__name__check,
        .attrs             = iopsq__enum_val__name__attrs,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
};
static iop_field_t const iopsq__enum_val__desc_fields[] = {
    {
        .name      = LSTR_IMMED("name"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_STRING,
        .data_offs = offsetof(iopsq__enum_val__t, name),
        .flags     = 1,
        .size      = fieldsizeof(iopsq__enum_val__t, name),
    },
    {
        .name      = LSTR_IMMED("val"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_OPTIONAL,
        .type      = IOP_T_I32,
        .data_offs = offsetof(iopsq__enum_val__t, val),
        .size      = fieldsizeof(iopsq__enum_val__t, val),
    },
};
const iop_struct_t iopsq__enum_val__s = {
    .fullname   = LSTR_IMMED("iopsq.EnumVal"),
    .fields     = iopsq__enum_val__desc_fields,
    .ranges     = iop__ranges__3,
    .ranges_len = countof(iop__ranges__3) / 2,
    .fields_len = countof(iopsq__enum_val__desc_fields),
    .size       = sizeof(iopsq__enum_val__t),
    .flags      = 3,
    .fields_attrs = iopsq__enum_val__desc_fields_attrs,
};
iop_struct_t const * const iopsq__enum_val__sp = &iopsq__enum_val__s;

/* }}} */
/* Class iopsq.Enum {{{ */

static iop_field_t const iopsq__enum__desc_fields[] = {
    {
        .name      = LSTR_IMMED("values"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REPEATED,
        .type      = IOP_T_STRUCT,
        .data_offs = offsetof(iopsq__enum__t, values),
        .size      = sizeof(iopsq__enum_val__t),
        .u1        = { .st_desc = &iopsq__enum_val__s },
    },
};
static const iop_class_attrs_t iopsq__enum__class_s = {
    .parent            = &iopsq__package_elem__s,
    .class_id          = 3,
};
const iop_struct_t iopsq__enum__s = {
    .fullname   = LSTR_IMMED("iopsq.Enum"),
    .fields     = iopsq__enum__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(iopsq__enum__desc_fields),
    .size       = sizeof(iopsq__enum__t),
    .flags      = 15,
    .is_union   = false,
    .st_attrs   = NULL,
    .fields_attrs = NULL,
    {
        .class_attrs  = &iopsq__enum__class_s,
    }
};
iop_struct_t const * const iopsq__enum__sp = &iopsq__enum__s;

/* }}} */
/* Class iopsq.Union {{{ */

static int iopsq__union__fields__check(const void *ptr, int n)
{
    if (n < 1) {
        iop_set_err("violation of constraint %s (%d) on field %s: length=%d",
                    "minOccurs", 1, "fields", n);
        return -1;
    }
    return 0;
}
static iop_field_attr_t const iopsq__union__fields__attrs[] = {
    {
        .type = 0,
        .args = (iop_field_attr_arg_t[]){ { .v.i64 = 1LL } },
    },
};
static iop_field_attrs_t const iopsq__union__desc_fields_attrs[] = {
    {
        .flags             = 1,
        .attrs_len         = 1,
        .check_constraints = &iopsq__union__fields__check,
        .attrs             = iopsq__union__fields__attrs,
    },
};
static iop_field_t const iopsq__union__desc_fields[] = {
    {
        .name      = LSTR_IMMED("fields"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REPEATED,
        .type      = IOP_T_STRUCT,
        .data_offs = offsetof(iopsq__union__t, fields),
        .flags     = 3,
        .size      = sizeof(iopsq__field__t),
        .u1        = { .st_desc = &iopsq__field__s },
    },
};
static const iop_class_attrs_t iopsq__union__class_s = {
    .parent            = &iopsq__structure__s,
    .class_id          = 4,
};
const iop_struct_t iopsq__union__s = {
    .fullname   = LSTR_IMMED("iopsq.Union"),
    .fields     = iopsq__union__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(iopsq__union__desc_fields),
    .size       = sizeof(iopsq__union__t),
    .flags      = 15,
    .is_union   = false,
    .st_attrs   = NULL,
    .fields_attrs = iopsq__union__desc_fields_attrs,
    {
        .class_attrs  = &iopsq__union__class_s,
    }
};
iop_struct_t const * const iopsq__union__sp = &iopsq__union__s;

/* }}} */
/* Structure iopsq.Package {{{ */

static int iopsq__package__name__check(const void *ptr, int n)
{
    for (int j = 0; j < n; j++) {
        lstr_t    val = IOP_FIELD(lstr_t   , ptr, j);

        for (int c = 0; c < val.len; c++) {
            switch (val.s[c]) {
                case 'a' ... 'z':
                case '_':
                case '.':
                    break;
                default:
                    iop_set_err("violation of constraint %s (%s) on field %s: %*pM",
                                "pattern", "[a-z_\\.]*", "name", LSTR_FMT_ARG(val));
                    return -1;
            }
        }
        if (val.len < 1) {
            iop_set_err("violation of constraint %s (%d) on field %s: length=%d",
                        "minLength", 1, "name", val.len);
            return -1;
        }
    }
    return 0;
}
static iop_field_attr_t const iopsq__package__name__attrs[] = {
    {
        .type = 9,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("[a-z_\\.]*") } },
    },
    {
        .type = 7,
        .args = (iop_field_attr_arg_t[]){ { .v.i64 = 1LL } },
    },
};
static iop_field_attrs_t const iopsq__package__desc_fields_attrs[] = {
    {
        .flags             = 640,
        .attrs_len         = 2,
        .check_constraints = &iopsq__package__name__check,
        .attrs             = iopsq__package__name__attrs,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
};
static iop_field_t const iopsq__package__desc_fields[] = {
    {
        .name      = LSTR_IMMED("name"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_STRING,
        .data_offs = offsetof(iopsq__package__t, name),
        .flags     = 1,
        .size      = fieldsizeof(iopsq__package__t, name),
    },
    {
        .name      = LSTR_IMMED("elems"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REPEATED,
        .type      = IOP_T_STRUCT,
        .data_offs = offsetof(iopsq__package__t, elems),
        .size      = sizeof(iopsq__package_elem__t *),
        .u1        = { .st_desc = &iopsq__package_elem__s },
    },
};
const iop_struct_t iopsq__package__s = {
    .fullname   = LSTR_IMMED("iopsq.Package"),
    .fields     = iopsq__package__desc_fields,
    .ranges     = iop__ranges__3,
    .ranges_len = countof(iop__ranges__3) / 2,
    .fields_len = countof(iopsq__package__desc_fields),
    .size       = sizeof(iopsq__package__t),
    .flags      = 3,
    .fields_attrs = iopsq__package__desc_fields_attrs,
};
iop_struct_t const * const iopsq__package__sp = &iopsq__package__s;

/* }}} */
/* Package iopsq {{{ */

static const iop_pkg_t *const iopsq__deps[] = {
    NULL,
};

static const iop_enum_t *const iopsq__enums[] = {
    &iopsq__int_size__e,
    &iopsq__string_type__e,
    NULL,
};

static const iop_struct_t *const iopsq__structs[] = {
    &iopsq__int_type__s,
    &iopsq__iop_type__s,
    &iopsq__package_elem__s,
    &iopsq__value__s,
    &iopsq__opt_info__s,
    &iopsq__field__s,
    &iopsq__structure__s,
    &iopsq__struct__s,
    &iopsq__enum_val__s,
    &iopsq__enum__s,
    &iopsq__union__s,
    &iopsq__package__s,
    NULL,
};

static const iop_iface_t *const iopsq__ifaces[] = {
    NULL,
};

static const iop_mod_t *const iopsq__mods[] = {
    NULL,
};

iop_pkg_t const iopsq__pkg = {
    .name    = LSTR_IMMED("iopsq"),
    .deps    = iopsq__deps,
    .enums   = iopsq__enums,
    .structs = iopsq__structs,
    .ifaces  = iopsq__ifaces,
    .mods    = iopsq__mods,
};
iop_pkg_t const * const iopsq__pkgp = &iopsq__pkg;

/* }}} */

