/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef IOP_HEADER_GUARD_iopsq_H
#define IOP_HEADER_GUARD_iopsq_H

#include "iopsq-t.iop.h"



/*----- package iopsq -----*/
EXPORT iop_pkg_t const iopsq__pkg;
EXPORT iop_pkg_t const * const nonnull iopsq__pkgp;

#endif
