/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef IOP_HEADER_GUARD_iopsq_TYPEDEFS_H
#define IOP_HEADER_GUARD_iopsq_TYPEDEFS_H

#include <lib-common/core.h>
#include <lib-common/iop-internals.h>

typedef enum iopsq__int_size__t {
    INT_SIZE_S8,
    INT_SIZE_S16,
    INT_SIZE_S32,
    INT_SIZE_S64,
} iopsq__int_size__t;
typedef IOP_ARRAY_OF(enum iopsq__int_size__t) iopsq__int_size__array_t;
#ifdef OPT_OF
typedef OPT_OF(enum iopsq__int_size__t) iopsq__int_size__opt_t;
#else
typedef IOP_OPT_OF(enum iopsq__int_size__t) iopsq__int_size__opt_t;
#endif
#define INT_SIZE_count 4
#define INT_SIZE_min   0
#define INT_SIZE_max   3

typedef enum iopsq__string_type__t {
    STRING_TYPE_STRING,
    STRING_TYPE_BYTES,
    STRING_TYPE_XML,
} iopsq__string_type__t;
typedef IOP_ARRAY_OF(enum iopsq__string_type__t) iopsq__string_type__array_t;
#ifdef OPT_OF
typedef OPT_OF(enum iopsq__string_type__t) iopsq__string_type__opt_t;
#else
typedef IOP_OPT_OF(enum iopsq__string_type__t) iopsq__string_type__opt_t;
#endif
#define STRING_TYPE_count 3
#define STRING_TYPE_min   0
#define STRING_TYPE_max   2

typedef struct iopsq__int_type__t iopsq__int_type__t;
typedef IOP_ARRAY_OF(iopsq__int_type__t) iopsq__int_type__array_t;

typedef struct iopsq__iop_type__t iopsq__iop_type__t;
typedef IOP_ARRAY_OF(iopsq__iop_type__t) iopsq__iop_type__array_t;

typedef struct iopsq__package_elem__t iopsq__package_elem__t;
typedef IOP_ARRAY_OF(iopsq__package_elem__t *nonnull ) iopsq__package_elem__array_t;

typedef struct iopsq__value__t iopsq__value__t;
typedef IOP_ARRAY_OF(iopsq__value__t) iopsq__value__array_t;

typedef struct iopsq__opt_info__t iopsq__opt_info__t;
typedef IOP_ARRAY_OF(iopsq__opt_info__t) iopsq__opt_info__array_t;

typedef struct iopsq__field__t iopsq__field__t;
typedef IOP_ARRAY_OF(iopsq__field__t) iopsq__field__array_t;

typedef struct iopsq__structure__t iopsq__structure__t;
typedef IOP_ARRAY_OF(iopsq__structure__t *nonnull ) iopsq__structure__array_t;

typedef struct iopsq__struct__t iopsq__struct__t;
typedef IOP_ARRAY_OF(iopsq__struct__t *nonnull ) iopsq__struct__array_t;

typedef struct iopsq__enum_val__t iopsq__enum_val__t;
typedef IOP_ARRAY_OF(iopsq__enum_val__t) iopsq__enum_val__array_t;

typedef struct iopsq__enum__t iopsq__enum__t;
typedef IOP_ARRAY_OF(iopsq__enum__t *nonnull ) iopsq__enum__array_t;

typedef struct iopsq__union__t iopsq__union__t;
typedef IOP_ARRAY_OF(iopsq__union__t *nonnull ) iopsq__union__array_t;

typedef struct iopsq__package__t iopsq__package__t;
typedef IOP_ARRAY_OF(iopsq__package__t) iopsq__package__array_t;

#endif
