<<<
== HTTP module ==

The goal of this module is to bind intersec http API to Python.

It works asynchronously. At API initialization, 3 Python callbacks are passed
as argument:

-  One to build http request headers,
-  a second to build http request body,
-  a last to parse server answer.

The request method takes as argument a Python object. When this method is
called, the API adds the request into a list. When the API processes the
request, it calls the 2 callbacks to build the request with Python object as
argument and send it. When the answer is received, the API calls the last
callback with the server answer.

This module declares 4 methods and 2 exceptions.

=== Details ===

==== http_initialize ====

parameters:

-  httpc_cfg: http client configuration serialized in hexadecimal.
              IOPY type : package core HttpcCfg
[source,python]
----
core = iopy.Plugin("path-to-my-libcommon-iop-core.so")
#default values
my_httpc_cfg = core.core.HttpcCfg(pipelineDepth = 32,
                                  noactDelay = 30000,
                                  maxQueries = 1024,
                                  onDataThreshold = 16384,
                                  headerLineMax = 1024,
                                  headerSizeMax = 65536)
cfg_hex = my_httpc_cfg().__hex__()
----

-  cb_build_headers:
   Python function which builds http request headers. It must return http
   headers as string. Receives the Python object passed to http_query.
-  cb_build_body:
   Python function which builds http request body. It must return http body as
   string. Receives the Python object passed to http_query.
-  cb_parse_answer:
   Python function which parses the server answer. return 0 on success and -1
   on fail (see below http_query callback argument). Receives the server
   string answer as parameter.
-  url: string.
-  url_arg: string
-  port: int
-  http_method: type IOPY: package core HttpMethod.
-  maxconn: max connection number.
-  maxrate: request per second maximum number.
-  user: string.
-  password: string.

==== http_loop ====

Creates a lib-common event named blocker. Call is blocking.
No parameter.

==== http_shutdown ====

Wipes and closes the API.
No parameter.

==== http_query ====

Creates a http request.
parameters:

-  ctx:
   any kind of Python object. This object will be passed to the build headers
   and build body callbacks.
-  cb_query_done:
   this callback is called when the http request has been processed (see
   below).
-  url: string.

cb_query_done parameters:

-  ctx: Python object passed to http_query.
-  status: see below.
-  err_msg: if status is -1 an error message is set.

status meaning:

-  0 means success to send request and answer processed.
-  -1 means fails to send request.
-  -2 means that your parse answer callback does not return 0.

=== example ===
[source,python]
----
def build_header(arg):
  return "Content-type: text/html"

def build_body(arg):
  return ""

def parse_answer(answer):
  print answer
  return 0

def query_end(arg, status, err_str):
  print "%s-%d-%s" % (arg, status, err_str)
  return 0

core = iopy.Plugin("path-to-my-libcommon-iop-core.so")
http_initialize(core.core.HttpcCfg().__hex__(), build_header, build_body, parse_answer, "www.google.fr", "", 80, 1, 5, 5000, "", "")
cbk_arg = "I m a http cbk arg. I could be any kind of python object"

http_query(cbk_arg, query_end, "/")
http_loop()
http_shutdown()
----
