/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#if !defined(linux) && !defined(__APPLE__)
#  warning "attrs_multi_valid.iop assumed linux alignments"
#endif
#ifndef __x86_64__
#  warning "attrs_multi_valid.iop assumed x86_64 alignments"
#endif

#include "attrs_multi_valid.iop.h"

/* Union attrs_multi_valid.MyUnion {{{ */

static iop_field_t const attrs_multi_valid__my_union__desc_fields[] = {
    {
        .name      = LSTR_IMMED("a"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(attrs_multi_valid__my_union__t, a),
        .size      = fieldsizeof(attrs_multi_valid__my_union__t, a),
    },
    {
        .name      = LSTR_IMMED("b"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I64,
        .data_offs = offsetof(attrs_multi_valid__my_union__t, b),
        .size      = fieldsizeof(attrs_multi_valid__my_union__t, b),
    },
    {
        .name      = LSTR_IMMED("c"),
        .tag       = 3,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_STRING,
        .data_offs = offsetof(attrs_multi_valid__my_union__t, c),
        .size      = fieldsizeof(attrs_multi_valid__my_union__t, c),
    },
    {
        .name      = LSTR_IMMED("d"),
        .tag       = 4,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_DOUBLE,
        .data_offs = offsetof(attrs_multi_valid__my_union__t, d),
        .size      = fieldsizeof(attrs_multi_valid__my_union__t, d),
    },
};
static int const iop__ranges__1[] = {
    0, 1,
    4,
};
const iop_struct_t attrs_multi_valid__my_union__s = {
    .fullname   = LSTR_IMMED("attrs_multi_valid.MyUnion"),
    .fields     = attrs_multi_valid__my_union__desc_fields,
    .ranges     = iop__ranges__1,
    .fields_len = countof(attrs_multi_valid__my_union__desc_fields),
    .ranges_len = countof(iop__ranges__1) / 2,
    .size       = sizeof(attrs_multi_valid__my_union__t),
    .is_union   = true,
};

/* }}} */
/* Structure attrs_multi_valid.Toto {{{ */

static int attrs_multi_valid__toto__b__check(const void *ptr, int n)
{
    for (int j = 0; j < n; j++) {
        attrs_multi_valid__my_union__t *val = &IOP_FIELD(attrs_multi_valid__my_union__t, ptr, j);

        switch (val->iop_tag) {
          case attrs_multi_valid__my_union__a__ft:
            break;
          case attrs_multi_valid__my_union__b__ft:
            break;
          case attrs_multi_valid__my_union__c__ft:
            iop_set_err("violation of constraint allow (c) on field b");
            return -1;
          case attrs_multi_valid__my_union__d__ft:
            iop_set_err("violation of constraint allow (d) on field b");
            return -1;
        }
    }
    return 0;
}
static int attrs_multi_valid__toto__c__check(const void *ptr, int n)
{
    for (int j = 0; j < n; j++) {
        attrs_multi_valid__my_union__t *val = &IOP_FIELD(attrs_multi_valid__my_union__t, ptr, j);

        switch (val->iop_tag) {
          case attrs_multi_valid__my_union__a__ft:
            break;
          case attrs_multi_valid__my_union__b__ft:
            iop_set_err("violation of constraint allow (b) on field c");
            return -1;
          case attrs_multi_valid__my_union__c__ft:
            break;
          case attrs_multi_valid__my_union__d__ft:
            iop_set_err("violation of constraint allow (d) on field c");
            return -1;
        }
    }
    return 0;
}
static iop_field_attrs_t const attrs_multi_valid__toto__desc_fields_attrs[] = {
    {
        .flags             = 0,
        .attrs_len         = 0,
        .check_constraints = &attrs_multi_valid__toto__b__check,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
        .check_constraints = &attrs_multi_valid__toto__c__check,
    },
};
static iop_field_t const attrs_multi_valid__toto__desc_fields[] = {
    {
        .name      = LSTR_IMMED("b"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_UNION,
        .data_offs = offsetof(attrs_multi_valid__toto__t, b),
        .flags     = 1,
        .size      = sizeof(attrs_multi_valid__my_union__t),
        .u1        = { .st_desc = &attrs_multi_valid__my_union__s },
    },
    {
        .name      = LSTR_IMMED("c"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_UNION,
        .data_offs = offsetof(attrs_multi_valid__toto__t, c),
        .flags     = 1,
        .size      = sizeof(attrs_multi_valid__my_union__t),
        .u1        = { .st_desc = &attrs_multi_valid__my_union__s },
    },
};
static int const iop__ranges__2[] = {
    0, 1,
    2,
};
const iop_struct_t attrs_multi_valid__toto__s = {
    .fullname   = LSTR_IMMED("attrs_multi_valid.Toto"),
    .fields     = attrs_multi_valid__toto__desc_fields,
    .ranges     = iop__ranges__2,
    .fields_len = countof(attrs_multi_valid__toto__desc_fields),
    .ranges_len = countof(iop__ranges__2) / 2,
    .size       = sizeof(attrs_multi_valid__toto__t),
    .flags      = 3,
    .fields_attrs = attrs_multi_valid__toto__desc_fields_attrs,
};

/* }}} */
/* Package attrs_multi_valid {{{ */

static const iop_pkg_t *const attrs_multi_valid__deps[] = {
    NULL,
};

static const iop_enum_t *const attrs_multi_valid__enums[] = {
    NULL,
};

static const iop_struct_t *const attrs_multi_valid__structs[] = {
    &attrs_multi_valid__my_union__s,
    &attrs_multi_valid__toto__s,
    NULL,
};

static const iop_iface_t *const attrs_multi_valid__ifaces[] = {
    NULL,
};

static const iop_mod_t *const attrs_multi_valid__mods[] = {
    NULL,
};

iop_pkg_t const attrs_multi_valid__pkg = {
    .name    = LSTR_IMMED("attrs_multi_valid"),
    .deps    = attrs_multi_valid__deps,
    .enums   = attrs_multi_valid__enums,
    .structs = attrs_multi_valid__structs,
    .ifaces  = attrs_multi_valid__ifaces,
    .mods    = attrs_multi_valid__mods,
};

/* }}} */

