/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef IOP_HEADER_GUARD_tstgen_TYPES_H
#define IOP_HEADER_GUARD_tstgen_TYPES_H

#include "tstgen-tdef.iop.h"

extern iop_enum_t const tstgen__my_enum_a__e;
IOP_ENUM(tstgen__my_enum_a);

typedef tstgen__my_enum_a__t my_enum_a__t;
typedef tstgen__my_enum_a__array_t my_enum_a__array_t;
#define my_enum_a__e  tstgen__my_enum_a__e

struct tstgen__my_struct_a__t {
    int32_t  i;
    int32_t  j;
    double   d1;
};
extern iop_struct_t const tstgen__my_struct_a__s;
IOP_GENERIC(tstgen__my_struct_a);

typedef tstgen__my_struct_a__t my_struct_a__t;
typedef tstgen__my_struct_a__array_t my_struct_a__array_t;
#define my_struct_a__s  tstgen__my_struct_a__s

struct tstgen__my_class_a__t {
    const iop_struct_t *__vptr;
};
extern iop_struct_t const tstgen__my_class_a__s;
IOP_CLASS(tstgen__my_class_a);

#define tstgen__my_class_a__class_id  0

typedef tstgen__my_class_a__t my_class_a__t;
typedef tstgen__my_class_a__array_t my_class_a__array_t;
#define my_class_a__s  tstgen__my_class_a__s

#endif
