DEPTH=..
include $(DEPTH)/admin/header.mk

__EXE__ =
__LIB__ = libcommon

libcommon_SOURCES = \
	array.c \
	blob.c \
	concatbin.c  \
	err_report.c  \
	string_is.c \
	timeval.c \
	unix.c

include $(DEPTH)/admin/footer.mk
