This object is used to describe the way log files are rotated, compressed and
purged.

`maxSize:int` (default 512MB)::
  The size which triggers a file rotation. If after writing a line, the
  file is larger than this size, the log file is rotated. Note that the
  trigger is launched when the limit is crossed, in other words this is
  not a strict maximum size for the file: a few log lines may be written
  before the file is really rotated.
  +
  0 or a negative value disables this rotation trigger. Note that it
  is unwise to disable this setting since many tools are still not
  adapted to the very large files (larger than 2G) properly.
`maxTime:ulong` (default 1 day)::
  This is the time after which a file rotation is triggered. This
  condition is lazily evaluated before any line is written. That means
  that if a log file is not much used, it is only rotated if needed. In
  other words, if you write every 3 hours in a file for which you set
  `maxTime` to 2 hours, it will actually be rotated every 3 hours.
  +
  0 or a negative value disables this rotation trigger.
`maxFiles:int` (default 0)::
  This is the maximum number of files kept for the log file in question.
  When a rotation occurs, if there are more than this amount of files,
  the older ones are deleted.
  +
  0 or a negative value disables this limit.
  +
  Note that only the most recent log file is used by the intersec product, and
  it is therefore safe for an external tool to remove the older log files while
  the intersec product is running.
`totalMaxSize:int` (default 1GB)::
  This is the maximum total size in bytes this log (old and last
  files included) is authorized to occupy on disk. When the total amount
  of disk used exceeds this limit, older log files are removed.
  +
  0 or a negative value disables this limit.
`compress:bool` (default true)::
  If this setting is set, older log files are compressed using
  `gzip -9`.

A valid log file configuration is:

-----------------------------------------------------------
{
    maxSize  = 1G;  # raise rotation size to 1Go
    maxFiles = 30;  # never have more than 30 files
    # use the defaults for the rest
}
-----------------------------------------------------------
