This section presents the JSONfootnote:[http://www.json.org/[]]-like format
used for Intersec configurations. This format is relaxed in many ways:

* string values may be put between apostrophes (`'`) or between quote
marks (`"`) indifferently;
* numeric values contains suffixes like `K/M/G` for sizes and `m/h/d`
for durations (minute, hour, day respectively);
* field/value separator may be either a colon (`:`) or an equal sign
(`=`);
* field separator may be either a comma (`,`) or a semicolon (`;`), and
trailing separators are allowed.
* `yes` and `true` are equivalent to `1`;
* `no` and `false` are equivalent to `0`.

This is of course a very quick description. It is important to know that
the configuration file is a strict JSON superset. So, in case of doubt,
use the canonical JSON form. Some examples of properly formatted files
follow here as examples:

--------------------------------------
# In Pure JSON
{
    "id":        "My ID",
    "strProp":   "string value",
    "intProp":   42,
    "floatProp": 3.14,
    "delay":     3600,
    "size":      1024,
    "array":     [ 0, 1, 2, 3, 4 ]
}
--------------------------------------

-----------------------------------------------------------------------------------------------
# The same with the Intersec enhancements
@id "My ID" { /* @field value { ... }  is a shorthand for  { "field": value, ... } */
    strProp   = "string value";
    intProp   = 42;
    floatProp = 3.14;
    delay     = 1h;       /* m/h/d/w for minute/hour/day/week */
    size      = 1K;       /* K/M/G/T for 2^{10/20/30/40}      */
    array     = [
        0, 1, 2, 3, 4
    ];                    /* trailing "comma" authorized      */
}
-----------------------------------------------------------------------------------------------

In the Intersec configuration file, parameters may be of 4 kinds:

mandatory without default value::
  This is a setting that must be set. Not doing so will result in a
  configuration parse error.
mandatory with a default value::
  This is a setting that does not need to be set explicitly. If it is
  not set, then the default value will be used instead.
optional::
  When it is set, the provisioned value is used. When it is not set, "no
  value" is set instead of a default value.
repeated::
  A repeated field is an array of similar objects or values. If the
  field is not explicitly set, then an empty array of objects or values
  is assumed.

Finally, each parameter expects a specific type. This can either be a
scalar value (string, boolean, number) or a complex type (Object,
Union). The following scalar types exist:

[width="100%",cols="<12%,<44%,<44%",options="header",]
|=======================================================================
|Type
|Comment
|Values

|`bool`
|Boolean values
|true, false, 0, 1, yes, no

|`byte`
|signed integer values on 1 octet
|-128 to 127

|`short`
|signed integer values on 2 octets
|-32768 to 32767

|`int`
|signed integer values on 4 octets
|-2^31^ to 2^31^-1

|`long`
|signed integer values on 8 octets
|-2^63^ to 2^63^-1

|`ubyte`
|unsigned integer values on 1 octet
|0 to 256

|`ushort`
|unsigned integer values on 2 octets
|0 to 65535

|`uint`
|unsigned integer values on 4 octets
|0 to 2^32^-1

|`ulong`
|unsigned integer values on 8 octets
|0 to 2^64^-1

|`double`
|double precision floating point number
|10.29e28, 1.12, 0.238e-12, ...

|`enum`
|signed integer with magic values
|some strings are allowed, depends on the enum

|`string`
|any utf-8 string
|"", "toto", "with escapes\n", ...

|`Object`
|a group of parameters inside of braces
|`{ a = [...], b = [...] }`

|`Union`
|a choice between a list of parameters inside of braces and which
the chosen member begin by a dot
|`.a: { [...] }`
|=======================================================================
