This section presents the JSONfootnote:[http://www.json.org/[]]-like format
used for Intersec configurations.

include::json-conformance.adoc[]

In the Intersec configuration file, parameters may be of 4 kinds:

mandatory without default value::
  This is a setting that must be set. Not doing so will result in a
  configuration parse error.
mandatory with a default value::
  This is a setting that does not need to be set explicitly. If it is
  not set, then the default value will be used instead.
optional::
  When it is set, the provisioned value is used. When it is not set, "no
  value" is set instead of a default value.
repeated::
  A repeated field is an array of similar objects or values. If the
  field is not explicitly set, then an empty array of objects or values
  is assumed.

Finally, each parameter expects a specific type. This can either be a
scalar value (string, boolean, number) or a complex type (Object,
Union). The following scalar types exist:

[width="100%",cols="<12%,<44%,<44%",options="header",]
|=======================================================================
|Type
|Comment
|Values

|`bool`
|Boolean values
|true, false, 0, 1, yes, no

|`byte`
|signed integer values on 1 octet
|-128 to 127

|`short`
|signed integer values on 2 octets
|-32768 to 32767

|`int`
|signed integer values on 4 octets
|-2^31^ to 2^31^-1

|`long`
|signed integer values on 8 octets
|-2^63^ to 2^63^-1

|`ubyte`
|unsigned integer values on 1 octet
|0 to 256

|`ushort`
|unsigned integer values on 2 octets
|0 to 65535

|`uint`
|unsigned integer values on 4 octets
|0 to 2^32^-1

|`ulong`
|unsigned integer values on 8 octets
|0 to 2^64^-1

|`double`
|double precision floating point number
|10.29e28, 1.12, 0.238e-12, ...

|`enum`
|signed integer with magic values
|some strings are allowed, depends on the enum

|`string`
|any utf-8 string
|"", "toto", "with escapes\n", ...

|`Object`
|a group of parameters inside of braces
|`{ a = [...], b = [...] }`

|`Union`
|a choice between a list of parameters inside of braces and which
the chosen member begin by a dot
|`.a: { [...] }`
|=======================================================================

The Intersec JSON parser also supports file inclusion in JSON files with the
`@include` syntax:
-------------------------------------------
{
    "schema": {
        "_class": "bigdata.schema.Schema",
        "collections": [
            @include("contracts.json"),
            @include("accounts.json")
        ]
    }
}
-------------------------------------------

It is supported for the following types:

unions, structs and classes::
    The content of the file is expected to be a json file (and of course,
    there can be an inclusion in an included file; circular inclusions are
    detected and forbidden).
strings, XML and data::
    The content of the included file directly contains the value of the field.

The paths of the files can be absolute, or relative to the original file
directory.

The inclusion follows symbols links. That means if you have the following
directory structure:
--------------------------------------
.
|-- dev/
|   |-- cfg.json -> ../prod/cfg.json
|   |-- mcms.json
|-- prod/
    |-- cfg.json
    |-- mcms.json
--------------------------------------
With the following `cfg.json`:
--------------------------------------
{
    "product": @include("mcms.json")
}
--------------------------------------
When unpacking `dev/cfg.json`, the Intersec JSON parser will include
`prod/mcms.json` and not `dev/mcms.json`.
