The JSON format is fully handled by the platform, moreover in order to
ease some usages a JSON superset has been implemented:

* string values may be put between apostrophes (`'`) or between quote
marks (`"`) indifferently;
* numeric values contains suffixes like `K/M/G` for sizes and `m/h/d`
for durations (minute, hour, day respectively);
* field/value separator may be either a colon (`:`) or an equal sign
(`=`);
* field separator may be either a comma (`,`) or a semicolon (`;`), and
trailing separators are allowed;
* `yes` and `true` are equivalent to `1`;
* `no` and `false` are equivalent to `0`;
* C-like comments are ignored.

But in any case, it is important to know that it's a strict JSON superset.
So, in case of doubt, the canonical JSON form will work.
Some examples of properly formatted JSON follow here as examples:

--------------------------------------
# In Pure JSON
{
    "id":        "My ID",
    "strProp":   "string value",
    "intProp":   42,
    "floatProp": 3.14,
    "delay":     3600,
    "size":      1024,
    "array":     [ 0, 1, 2, 3, 4 ]
}
--------------------------------------

-----------------------------------------------------------------------------------------------
# The same with the Intersec enhancements
@id "My ID" { /* @field value { ... }  is a shorthand for  { "field": value, ... } */
    strProp   = "string value";
    intProp   = 42;
    floatProp = 3.14;
    delay     = 1h;       /* m/h/d/w for minute/hour/day/week */
    size      = 1K;       /* K/M/G/T for 2^{10/20/30/40}      */
    array     = [
        0, 1, 2, 3, 4
    ];                    /* trailing "comma" authorized      */
}
-----------------------------------------------------------------------------------------------

