name: Deploy
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update -y && \
          sudo apt-get install -y \
            clang \
            curl \
            exuberant-ctags \
            flex \
            gperf \
            libclang-dev \
            libssl-dev \
            libxml2-dev \
            llvm-dev \
            pkg-config \
            python3-dev \
            python3-pip \
            smitools \
            snmp-mibs-downloader \
            valgrind \
            doxygen \
            graphviz
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Update pip and install virtualenv
        run: |
          sudo python3 -m pip install --upgrade pip && \
          sudo python3 -m pip install virtualenv

      - name: Install poetry
        run: curl -sL https://install.python-poetry.org | python3 - -y

      - name: Update PATH for poetry
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install waf
        run: |
          sudo curl https://waf.io/waf-2.0.24 -o /usr/local/bin/waf && \
          sudo chmod +x /usr/local/bin/waf && \
          sudo waf --help 2>&1 >/dev/null

      - name: Configure with Clang, default
        run: waf configure
        env:
          CC: clang
          CXX: clang++

      - name: Build doc using doxygen
        run: waf doxygen

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Default Doxyfile build documentation to html directory.
          # Change the directory if changes in Doxyfile
          publish_dir: ./docs/doxygen
